config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  root "groups#index"
  resources :users, only: [:edit, :update, :destroy, :show]
  resources :groups, only: [:index, :new, :create, :edit, :update]do
    resources :photos, only: [:index, :new, :create, :show, :destroy]
  end
end
    

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :photos
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :image, presence: true
  validates :name, presence: true
  validates :nated_food, presence: true
  validates :dislike_word, presence: true
  validates :hate_human, presence: true
  validates :weaknes, presence: true
  validates :remark, presence: true
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  # validates :password, presence: true, length: {minimum: 6}, allow_blank: true
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :photos

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'      
    else
      render :new  
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path,notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids:[])
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_group
  before_action :set_photos
  before_action :set_photo, only:[:show, :destroy]
  
  def index
    @groups = Group.new
    @photos = @group.photos.includes(:user)
  end

  def new
    @photo = Photo.new
  end
  
  def create
    @photo = @group.photos.new(photo_params)
    if @photo.save
      redirect_to group_photos_path(@group), notice: 'my truthを作成しました'
    else
      @photos = @group.photos.includes(:user)
      flash.now[:alert] = '入力してください。'
      render :new
    end
  end

  def show
  end

  def destroy
    @photo.destroy
    redirect_to root_path,notice:'削除に成功しました'
  end


  private
  def photo_params
    params.require(:photo).permit(:name,:image,:nated_food,:dislike_word,:hate_human,:weaknes,:remark).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_photos
    @photos = Photo.all
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
    @user = User.find(params[:id])
    user.save
    redirect_to user_path(id: current_user)
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_grouptop.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    .contents__user__box
      = current_user.name
    

app/views/groups/edit.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    .contents__user__box
      = current_user.name

.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render "grouptop"
  = render "photos/main_bar"
  = render "photos/under_bar"

app/views/groups/new.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    .contents__user__box
      = current_user.name

.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head 
    %meta{:content => "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    -# "http-equiv"後の=>を:に修正
    %title MyTruth
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/photos/_main_bar.html.haml
.main
  .side
    .side__group
      グループ名
    - current_user.groups.each do |group|
      .group-list
        = link_to group_photos_path(group) do
          .group-list__box 
            %p
              = group.name
  .photo__space
    = render partial: 'photos/photo', collection: @photos
      

app/views/photos/_photo.html.haml
.photo{data: {photo: {id: photo.id}}}
  %a
    = link_to "photos/#{photo.id}",methos: :get do
      = image_tag "#{photo.image.url}",height:"250px",width:"250px"
      %p
        = photo.name

app/views/photos/_top_bar.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    .contents__user__box
      = current_user.name
    .contents__user__group
      .contents__user__group__box
        = @group.name
       
    .contents__form
      = form_for"#" do |f|
        = f.text_field :content, class:'user-search',placeholder: "user search"
        = f.submit '検索',class: 'submit-btn'
    .contents__post
      = link_to new_group_photo_path(@group),class:"post-btn" do
        投稿する
        

app/views/photos/_under_bar.html.haml
.menu
  .menu__list
    = link_to "#",class: "icon-btn" do
      = icon('fas','home')
      %span<>
    = link_to new_group_path,method: :get,class: "icon-btn" do
      = icon('fas','edit')
      %span<>
    = link_to "#",class: "icon-btn" do
      = icon('fas','crown')
      %span<>
    = link_to edit_user_path(current_user) do
      = icon('fas','cog',class:'icon-btn')
      %span<>
  .menu__user
    = link_to destroy_user_session_path, method: :delete, class: "user-btn" do
      ログアウト

app/views/photos/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。

app/views/photos/index.html.haml
.wrapper
  = render "top_bar"
  = render "main_bar"
  = render "under_bar"
  

app/views/photos/new.html.haml
.wrapper
  = render "groups/grouptop"
  .container
    = form_for [@group,@photo] do |form|
      .form_center
        %p1 新規投稿
        %br
        %a ニックネーム：
        %a{class: "condition"}必須
        %br
        = form.text_area :name, class: "text_space",placeholder: "ニックネーム"

        %br
        %a 変顔写真：
        %a{class: "condition"}必須
        %br
        = form.file_field :image, class: "text_space",placeholder: "Image Url"
        %br
        %a 嫌いな食べ物：
        %a{class: "condition"}必須
        = form.text_area :nated_food, class: "text_space",placeholder: "例：ニンジン"
        %br
        %a 嫌いな言葉：
        %a{class: "condition"}必須
        = form.text_area :dislike_word, class: "text_space",placeholder: "例：あほ"
        %br
        %a 嫌いな人間：
        %a{class: "condition"}必須
        = form.text_area :hate_human, class: "text_space",placeholder: "例：ケチなやつ"
        %br
        %a 弱点：
        %a{class: "condition"}必須
        = form.text_area :weaknes, class: "text_space",placeholder: "例：脇腹"
        %br
        %a コメント：
        %a{class: "condition"}必須
        %br
        = form.text_area :remark, class: "text_space",placeholder: "コメント"
        %br
        %br
        = form.submit "SEND",class: "send_btn"

app/views/photos/show.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    .contents__user__box
      = current_user.name
    .contents__user__group
      .contents__user__group__box
        = @group.name

.photo__space2
  .card__space
    .card__space__card
      .photoImage
        = image_tag "#{@photo.image}",height:"250px",width:"250px"
      .photoContents
        %a2 名前：
        = @photo.name
      .postText
        %a3
          嫌いな食べ物：
        %a3
          =@photo.nated_food
        %br
        %br
          %a3
            嫌いな人間：
          %a3
            =@photo.hate_human
        %br
          %a3
            嫌いな言葉：
          %a3
            =@photo.dislike_word
        %br
          %a3
            弱点：
          %a3
            =@photo.weaknes
        %br
          %a3
            コメント：
          %a3
            =@photo.remark
    .truth__delete
      = link_to group_photo_path, method: :delete, class:"delete_btn" do
        削除する

app/views/users/edit.html.haml
.title
  .title__header
    MY TRUTH
.contents
  .contents__user
    

#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path,method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'